### ISSUE TITLE
passwords appears in functions

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#142]
There are a few places in which specific passwords are embedded in the code. This should be removed.
The proper way to deal with passwords is to put them in the config/local directory.
This directory has a .gitignore, and therefore is not distributed to other users when you commit some changes.
My suggestion is that we will have a passwords config file containing:
PasswordName : User, Password, {UsedbyFuns}

Lets talk about this.

**Comment by agioffe** [comment]
I agree, will try to implement.

**Comment by EranOfek** [comment]
A simple design:

PasswordManager class  < Component

methods
[User, Pass] = searchPassByName(Obj, Name)
searchPassByFun(Obj, Fun), if Fun empty, then use stack to id the calling
function
searchPass

Config should be of the format:
Name:   User, Pass, optional_calling_fun1, optional_calling_fun2,...

**Comment by EranOfek** [comment]
new class PasswordsManager is ready.
Examples.Passwords.yml file isn in the config/ dir

**Comment by agioffe** [comment]
Dear Eran,
I wished to implement this into db.AstroDb, but
the class initialization does not work for me:
>> clear all
>> C=Configuration;
>> C.reloadSysConfig;
>> PM = PasswordsManager('/home/sasha/matlab/AstroPack/config/Pass.yml');
Error using rmfield (line 20)
S must be a structure array.

Error in PasswordsManager (line 47)
            Obj.Passwords = rmfield(Obj.Passwords, 'FileName');
 
>> 
Here is the config file:
sasha@last11e:~$ cat /home/sasha/matlab/AstroPack/config/Pass.yml
LASTDb : ['postgres', 'PassRoot', '', '']
sasha@last11e:~$

**Comment by EranOfek** [comment]
fixed

**Comment by agioffe** [comment]
C=Configuration;
C.reloadSysConfig

ans = 

  Configuration with properties:

        ConfigName: []
              Path: '/home/sasha/matlab/AstroPack/matlab/base/@Configuration/../../../config'
      ExternalPath: '/home/sasha/matlab/AstroPack/matlab/base/@Configuration/../../external'
              Data: [1×1 struct]
    InputArgsLevel: 'InputArgs'

!cat /home/sasha/matlab/AstroPack/config/Passwords.yml
LASTDb : ['postgres', 'PassRoot', '', '']
>> PM = PasswordsManager('/home/sasha/matlab/AstroPack/config/Passwords.yml');
>> PM.Passwords

ans =

     []

>> PM.PassFile

ans =

    'Passwords'
>> PM.search('LASTDb')
Error using PasswordsManager/search (line 84)
Passwords configuration file Passwords was not found
 
>>

**Comment by EranOfek** [comment]
FIXED

**Comment by EranOfek** [comment]
why is this opened?

**Comment by agioffe** [comment]
After pulling it still does not see the passwords:

>> PM = PasswordsManager('/home/sasha/matlab/AstroPack/config/Passwords.yml');
>> PM.Passwords

ans =

     []

Probably, the last version has not been pushed?
