### ISSUE TITLE
Scheduler demon doesn't load correctly target files

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#513]
Even after my minor changes of b0aa83b9a, I have not been able to load correctly the target file made today by Ruslan.
To test load it with `telescope.Scheduler.demon('TargetList','/home/ocs/ObservationSchedule.csv')`. The file is on last0.
My first change of line 834 is because it appears that you cannot just assign a table to an empty object; however even after that workaround (which might be incorrect), the demon stumbles onto
```
Operator '-' is not supported for operands of type 'table'.

Error in telescope.Scheduler/get.HA (line 262)
            Val       = Obj.LST - Obj.RA;

Error in telescope.Scheduler/weight (line 1834)
            HA_Day  = Obj.HA./360;  % [day]

Error in telescope.Scheduler/selectTarget (line 1733)
            W   = Obj.weight(JD);

Error in telescope.Scheduler/serviceTargetRequests (line 947)
                [TargetInd, Priority, Tbl, Struct] = S.selectTarget(JD,...

Error in telescope.Scheduler.demon (line 1041)
                S.serviceTargetRequests('ToO_File',Args.ToO_File,...
```
the moment is has to dispatch a target. The reason is that at that point `Obj.RA` is a **table**, whereas with the default survey tiling (i.e. calling just `telescope.Scheduler.demon`) it is an array of doubles, which can be then subtracted from `Obj.LST`.
I'm not familiar with all the mechanics of catalogs, so please help.

@RuslanKonno : next time, please dry-run the lists at day time (`S.send("Unit.observeAskingTargets('NoHardware',true,'SimulationJD',celestial.time.julday+0.5)")`)

**Comment by EastEriq** [comment]
Shorter way to reproduce the problem:
before https://github.com/EranOfek/AstroPack/commit/b0aa83b9ad697da290803ff798d269b24a4e1946
```
>> S=telescope.Scheduler;
>> S.loadTable('ObservationSchedule.csv');
Expected one output from a curly brace or dot indexing expression, but there were 0
results.

Error in telescope.Scheduler/loadTable (line 838)
                    ExistFieldName = Obj.List.Catalog.(Obj.ColFieldName);
```
After https://github.com/EranOfek/AstroPack/commit/b0aa83b9ad697da290803ff798d269b24a4e1946
```
>> S=telescope.Scheduler;
>> S.loadTable('ObservationSchedule.csv','replace');
>> S.selectTarget()
Operator '-' is not supported for operands of type 'table'.

Error in telescope.Scheduler/get.HA (line 262)
            Val       = Obj.LST - Obj.RA;

Error in telescope.Scheduler/weight (line 1834)
            HA_Day  = Obj.HA./360;  % [day]

Error in telescope.Scheduler/selectTarget (line 1733)
            W   = Obj.weight(JD);
```

**Comment by EranOfek** [comment]
Fixed using the following modification
loadTable now updates Ntarget and Ncol
Not sure what exactly happened, but it is working now.

**Comment by EastEriq** [comment]
There are still bugs:
1. this one is still present
```
>> S=telescope.Scheduler;
>> S.loadTable('ObservationSchedule.csv');
Expected one output from a curly brace or dot indexing expression, but there were 0 results.

Error in telescope.Scheduler/loadTable (line 842)
                    ExistFieldName = Obj.List.Catalog.(Obj.ColFieldName);
```
2.
```
>> S.loadTable('ObservationSchedule.csv','replace');
>> class(S.List.Catalog.FieldName(1))

ans =

    'double'
```
it should be a string. It might be because in @RuslanKonno's csv the content is written without quotes, but the mechanism should be made a bit more robust. Leaving it as a number affects the log message, the image filename and what not. All can be taken care downstream but it s better to fix it at the time of ingesting the table.

**Comment by EranOfek** [comment]
Problem 1 now fixed.
Problem 2 - in the new version of loadTables, if the FieldNames is numeric then it will be converted to strings.

**Comment by EastEriq** [comment]
To move on I committed a dirty fix for the second in 444f29521.
Note this further bug:
```
>> S=telescope.Scheduler;
>> S.loadTable('ObservationSchedule.csv','replace');
>> S.loadTable('ObservationSchedule.csv');
Error using telescope.Scheduler/loadTable (line 857)
Index exceeds the number of array elements (1535).
```

**Comment by EranOfek** [comment]
bug fixed.
[dev1 dc117bdcf]

**Comment by EastEriq** [comment]
You can then remove the num2str I inserted at my previous commit?

Il 4 nov 2024 14:03, Eran Ofek ***@***.***> ha scritto:
Caution: External Sender. Do not click on links or open attachments unless you recognize the sender.


bug fixed.
[dev1 dc117bd<https://github.com/EranOfek/AstroPack/commit/dc117bdcfe6210131acbbce3b6de51f3fc0eff10>]

**Comment by EranOfek** [comment]
can't recreate error

**Comment by EranOfek** [comment]
removed.
In general the best way to store characters in a table is via string array
(not cell array and not chars).

**Comment by EranOfek** [comment]
but this introduced a new error:
S=telescope.Scheduler;
>> S.loadTable('ObservationSchedule.csv','replace');
>> S.loadTable('ObservationSchedule.csv');
Error using setdiff
First argument must be text.

Error in telescope.Scheduler/loadTable (line 854)
                        [~,Ic]    = setdiff(NewFieldName, ExistFieldName);


checking

**Comment by EastEriq** [comment]
Can you guarantee that one way or the other of loading the table works by this evening?

**Comment by EranOfek** [comment]
Fixed using new function: tools.string.convert2strings
[dev1 355ea5c80]

**Comment by simonegarrappa** [comment]
Now with alphanumeric target names it returns a NaN that is registered in the filename/header.
e.g. target for mount 5 '4Cp2750' becomes 'NaN' as a string.



```
>> telescope.Scheduler.demon('TargetList','/home/ocs/ObservationSchedule.csv')
15:41:50.159 [INF] selecting target for mount 1, requested at JD=2460620.154047, now 2460620.154053
15:41:51.664 [INF] Mount=  1  Target =                 1392  RA=334.285714  Dec= 33.000000 Priority=  1.20  Nexp= 20 ExpTime= 20.0
15:41:51.692 [INF] selecting target for mount 5, requested at JD=2460620.154050, now 2460620.154070
15:41:52.713 [INF] Mount=  5  Target =                  NaN  RA=350.499426  Dec= 27.546234 Priority=  3.10  Nexp=400 ExpTime= 20.0
15:41:53.305 [INF] selecting target for mount 4, requested at JD=2460620.154057, now 2460620.154089
15:41:54.254 [INF] Mount=  4  Target =                  NaN  RA= 30.950000  Dec= 31.340000 Priority=  3.10  Nexp= 20 ExpTime= 20.0
15:41:54.269 [INF] selecting target for mount 6, requested at JD=2460620.154059, now 2460620.154100
15:41:56.370 [INF] Mount=  6  Target =                 1234  RA=336.428571  Dec= 21.000000 Priority=  1.20  Nexp= 20 ExpTime= 20.0
15:41:56.400 [INF] selecting target for mount 10, requested at JD=2460620.154064, now 2460620.154125
15:41:57.406 [INF] Mount= 10  Target =                 1314  RA=331.111111  Dec= 27.000000 Priority=  1.20  Nexp= 20 ExpTime= 20.0
15:41:57.424 [INF] selecting target for mount 2, requested at JD=2460620.154066, now 2460620.154137
```

**Comment by EranOfek** [comment]
Is the file name also contains NaN? Or is it ok?

**Comment by RuslanKonno** [comment]
Also, all targets with a dot extension are stripped of the dot extension.
e.g. "1234.ABC" in the .csv file becomes becomes "1234" when passed to mounts.

**Comment by simonegarrappa** [comment]
When it is misconverted as 'NaN' there is no field name in the image file.

e.g.
LAST.01.05.01_20241105.155807.508_clear__048_001_001_sci_raw_Image_1.fits

**Comment by EastEriq** [comment]
> Is the file name also contains NaN? Or is it ok?

Ah , I though that the filename is built from `Camera.Object` which is set to FieldName, so I would have expected NaN there too.

![image](https://github.com/user-attachments/assets/232151e9-a7ec-487f-906d-b9f1a7a598c1)

**Comment by EranOfek** [comment]
Fixed by modifying read2table - adding:
```
Opts = detectImportOptions(Data);
Ifn = find(strcmp(Opts.VariableNames, 'FieldName'));
Opts.VariableTypes{Ifn} = 'string';
Data = readtable(Data, Opts);
```
[dev1 21f273476]
