### ISSUE TITLE
Scheduler; Current schedule update scheme does not save NightCounter resets and ToO injections if Scheduler is restarted before observations

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#646]
Currently, the scheduler only updates the persistent file only if it fulfilled a schedule request from a mount; lines 1219 - 1243 in `telescope.Scheduler`

This means that no changes to the schedule will be saved to the file until the next time a schedule request is fulfilled, i.e., any changes made to the in-memory schedule will be lost if the scheduler process is killed.

This affects 

1. ToOs that may be injected at any time, e.g. at day time.
2. Retractions - same as ToOs
3. The NightCounter reset (line 1192), which occurs at NewNight defined as more than 0.9d since the last sunset (line 2089). If the scheduler is stopped or crashes during the day, then likely it will be restarted by shifters at the start of their shift, i.e, after sunset. So new observations will be taken without resetting the NightCounter. This was actually part of the issue in #638

The above changes to the in-memory schedule should thus also trigger an update of the persistent file in some capacity.

**Comment by RuslanKonno** [comment]
Looks like even when the scheduler is running un-interupted, the NightCounter isn't being reset properly.

**Comment by EranOfek** [comment]
Fixed, with some additional changes.
Also cleaned TargetList.mat on last0.

**Comment by RuslanKonno** [comment]
It's not fixed, because the persistent file is still only updated during observations (lines 1219 - 1243 in serviceTargetRequests) so any updates are lost when the scheduler is aborted.

**Comment by EranOfek** [comment]
I think this doesn't matter, because the new mechanism will catch this.

**Comment by RuslanKonno** [comment]
Then it addresses only point 3, not ToOs and Retractions.

**Comment by EastEriq** [comment]
Can we consider this closed, after #750 ?
